In [31]:
from tsp_solver import greedy
import pandas as pd
import numpy as np
from scipy.spatial import distance_matrix
import random

In [65]:
lst1 = [random.randint(1, 100) for i in np.arange(100)]
lst2 = [random.randint(1, 100) for i in np.arange(100)]
lst3 = range(100)
location_list = pd.DataFrame(
    {'xcord': lst1,
     'ycord': lst2
    })
print(location_list)
df = pd.DataFrame(location_list, columns=['xcord', 'ycord']) 
dist_mat = pd.DataFrame(distance_matrix(df.values, df.values))#, index=df.index)# , columns=df.index)
tri = np.tril(dist_mat)

    xcord  ycord
0      76     10
1       9     20
2      15     46
3      36     80
4      48      3
5      51     45
6      12     85
7      14     77
8      49     61
9      63     48
10     43     47
11     33     12
12     38     12
13     63     96
14     29     96
15     58     23
16     42     87
17     55     46
18     78     57
19     56     90
20     93    100
21     35     49
22     94     14
23     11     53
24     57     52
25     64     33
26     41     95
27     89      9
28     21     87
29     34     37
..    ...    ...
70     16     51
71     55     50
72     16     44
73     61     54
74     70     58
75     22     11
76     32     81
77      5     84
78     95     63
79     41     62
80     56     65
81     41     90
82     56     34
83     31     61
84     66     90
85     29     68
86     79     44
87     52     10
88     63     81
89     19     22
90      6     97
91     81     63
92     42     89
93     68     87
94     67     39
95     34     21
96     60     42
97     83     60
98     63     59
99     17      1

[100 rows x 2 columns]

In [66]:
df

    xcord  ycord
0      76     10
1       9     20
2      15     46
3      36     80
4      48      3
5      51     45
6      12     85
7      14     77
8      49     61
9      63     48
10     43     47
11     33     12
12     38     12
13     63     96
14     29     96
15     58     23
16     42     87
17     55     46
18     78     57
19     56     90
20     93    100
21     35     49
22     94     14
23     11     53
24     57     52
25     64     33
26     41     95
27     89      9
28     21     87
29     34     37
..    ...    ...
70     16     51
71     55     50
72     16     44
73     61     54
74     70     58
75     22     11
76     32     81
77      5     84
78     95     63
79     41     62
80     56     65
81     41     90
82     56     34
83     31     61
84     66     90
85     29     68
86     79     44
87     52     10
88     63     81
89     19     22
90      6     97
91     81     63
92     42     89
93     68     87
94     67     39
95     34     21
96     60     42
97     83     60
98     63     59
99     17      1

[100 rows x 2 columns]

In [67]:
greedy.solve_tsp(tri)

[1,
 30,
 38,
 89,
 41,
 31,
 55,
 29,
 45,
 62,
 95,
 61,
 12,
 11,
 75,
 99,
 39,
 34,
 4,
 87,
 51,
 37,
 0,
 50,
 67,
 57,
 15,
 47,
 82,
 25,
 94,
 96,
 9,
 43,
 73,
 24,
 35,
 71,
 17,
 5,
 10,
 69,
 21,
 40,
 63,
 72,
 2,
 70,
 23,
 65,
 53,
 77,
 52,
 90,
 6,
 54,
 7,
 60,
 28,
 68,
 14,
 26,
 81,
 92,
 16,
 3,
 76,
 85,
 83,
 79,
 8,
 46,
 44,
 80,
 59,
 19,
 13,
 84,
 48,
 20,
 36,
 93,
 88,
 56,
 66,
 78,
 64,
 42,
 97,
 91,
 49,
 18,
 32,
 74,
 98,
 86,
 33,
 58,
 22,
 27]

In [68]:
df

    xcord  ycord
0      76     10
1       9     20
2      15     46
3      36     80
4      48      3
5      51     45
6      12     85
7      14     77
8      49     61
9      63     48
10     43     47
11     33     12
12     38     12
13     63     96
14     29     96
15     58     23
16     42     87
17     55     46
18     78     57
19     56     90
20     93    100
21     35     49
22     94     14
23     11     53
24     57     52
25     64     33
26     41     95
27     89      9
28     21     87
29     34     37
..    ...    ...
70     16     51
71     55     50
72     16     44
73     61     54
74     70     58
75     22     11
76     32     81
77      5     84
78     95     63
79     41     62
80     56     65
81     41     90
82     56     34
83     31     61
84     66     90
85     29     68
86     79     44
87     52     10
88     63     81
89     19     22
90      6     97
91     81     63
92     42     89
93     68     87
94     67     39
95     34     21
96     60     42
97     83     60
98     63     59
99     17      1

[100 rows x 2 columns]